from pathlib import Path
import hashlib
import gc
import json

import h3
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import shape, Polygon
from shapely.ops import transform
from pyproj import Transformer


PERIODS = {
    "24_07": "h3_cl_24_07.parquet",
    "25_07": "h3_cl_25_07.parquet",
    "26_07": "h3_cl_26_07.parquet",
}

H3_RESOLUTION = 12
# We deliberately make the candidate area larger than the real 5 m buffer.
# Final selection is still done by exact intersection with the real 5 m buffer.
CANDIDATE_BUFFER_M = 30
FINAL_BUFFER_M = 5


def _progress(cb, n, msg):
    if cb:
        cb(int(n), msg)


def _find_col(df, candidates):
    lower = {str(c).lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lower:
            return lower[c.lower()]
    return None


def _prepare_lanes(input_path):
    g = gpd.read_file(input_path)

    if g.empty:
        raise ValueError("GeoJSON не содержит объектов.")

    cols = {str(c).lower(): c for c in g.columns}

    def pick(*names):
        for n in names:
            if n.lower() in cols:
                return cols[n.lower()]
        return None

    name_col = pick("name", "NAME")
    type_col = pick("type", "TYPE")
    status_col = pick("status", "STATUS")
    zone_col = pick("zone", "ZONE")

    g = g[g.geometry.notna() & ~g.geometry.is_empty].copy()
    g = g[g.geometry.geom_type.isin(["LineString", "MultiLineString"])].copy()

    if g.empty:
        raise ValueError("После очистки не осталось корректных линий.")

    # Work in WGS84 for H3.
    g = g.to_crs(4326)

    # Repair only invalid line geometries if any remain.
    invalid = ~g.geometry.is_valid
    if invalid.any():
        g.loc[invalid, "geometry"] = g.loc[invalid, "geometry"].buffer(0)
        g = g[g.geometry.geom_type.isin(["LineString", "MultiLineString"])].copy()

    g["velo_id"] = g.geometry.apply(
        lambda geom: hashlib.md5(geom.wkb).hexdigest()[:16]
    )
    g = g.drop_duplicates(subset=["velo_id"]).copy()

    g["name"] = g[name_col].fillna("").astype(str) if name_col else ""
    g["type"] = g[type_col].fillna("").astype(str) if type_col else ""
    g["status"] = g[status_col].fillna("").astype(str) if status_col else ""
    g["zone"] = g[zone_col].fillna("").astype(str) if zone_col else ""

    return g[["velo_id", "name", "type", "status", "zone", "geometry"]]


def _h3_cells_for_geometry(geometry):
    """Return H3 r12 cells covering a conservative candidate area around geometry.

    H3 is used as the spatial index. We do not load the 600k-cell WKT dictionary.
    The candidate area is intentionally wider than the final 5 m buffer; exact
    intersection with the 5 m buffer is performed afterwards.
    """
    candidate_geom = geometry.buffer(0) if not geometry.is_valid else geometry
    candidate_geom = candidate_geom.buffer(CANDIDATE_BUFFER_M / 111_320.0)

    # geo_to_cells expects a GeoJSON-like geometry in lon/lat.
    geojson = {
        "type": "Feature",
        "properties": {},
        "geometry": json.loads(gpd.GeoSeries([candidate_geom], crs=4326).to_json())[
            "features"
        ][0]["geometry"],
    }

    return set(h3.geo_to_cells(geojson, H3_RESOLUTION))


def _build_h3_candidates(lanes):
    """Generate velo_id -> H3 IDs directly from H3, without 600k polygons."""
    rows = []
    all_cells = set()

    total = len(lanes)
    for i, row in enumerate(lanes.itertuples(index=False), start=1):
        cells = _h3_cells_for_geometry(row.geometry)
        all_cells.update(cells)
        rows.extend((row.velo_id, cell) for cell in cells)

        if i == 1 or i % 50 == 0 or i == total:
            pct = 20 + int(20 * i / max(total, 1))
            print(f"H3 index: {i}/{total} lanes, unique candidates={len(all_cells):,}")

    if not rows:
        return pd.DataFrame(columns=["velo_id", "h3_id"])

    return pd.DataFrame(rows, columns=["velo_id", "h3_id"]).drop_duplicates()


def _h3_polygon(cell):
    # h3.cell_to_boundary returns (lat, lon) pairs.
    boundary = h3.cell_to_boundary(cell)
    return Polygon([(lon, lat) for lat, lon in boundary])


def _make_exact_intersections(lanes, candidates):
    """Exact final spatial check, but only for H3 IDs generated by H3 index."""
    if candidates.empty:
        return candidates

    # Build only candidate H3 polygons, not the full 600k dictionary.
    unique_cells = candidates["h3_id"].unique()
    h3_geo = gpd.GeoDataFrame(
        {"h3_id": unique_cells},
        geometry=[_h3_polygon(cell) for cell in unique_cells],
        crs=4326,
    )

    lanes_utm = lanes.to_crs(32637)
    lanes_buffered = lanes_utm[["velo_id", "geometry"]].copy()
    lanes_buffered["geometry"] = lanes_buffered.geometry.buffer(FINAL_BUFFER_M)

    h3_utm = h3_geo.to_crs(32637)

    joined = gpd.sjoin(
        lanes_buffered,
        h3_utm[["h3_id", "geometry"]],
        how="inner",
        predicate="intersects",
    )

    result = joined[["velo_id", "h3_id"]].drop_duplicates()
    return result


def _read_h3_period(path, needed_h3=None):
    """Read one period and immediately reduce it to relevant H3 IDs."""
    columns = None
    try:
        # Reading only the columns needed for the calculation keeps memory low.
        probe = pd.read_parquet(path, engine="pyarrow")
        h3_col = _find_col(probe, ["h3_id", "h3", "hexagon", "index"])
        trip_col = _find_col(probe, ["sum_trip", "trips", "trip_count", "count"])
        class_col = _find_col(probe, ["trip_class", "class", "cluster"])
        if not h3_col or not trip_col or not class_col:
            raise ValueError(
                f"Не удалось определить колонки H3 в {path.name}. "
                f"Найдены: {list(probe.columns)}"
            )
        columns = [h3_col, trip_col, class_col]
        del probe
    except Exception:
        raise

    df = pd.read_parquet(path, columns=columns, engine="pyarrow")
    df.columns = ["h3_id", "sum_trip", "trip_class"]
    df["h3_id"] = df["h3_id"].astype(str)
    df["sum_trip"] = pd.to_numeric(df["sum_trip"], errors="coerce")
    df["trip_class"] = pd.to_numeric(df["trip_class"], errors="coerce")
    df = df.dropna(subset=["h3_id", "sum_trip"])

    if needed_h3 is not None:
        df = df[df["h3_id"].isin(needed_h3)].copy()

    # Consolidate duplicate H3 rows if present in the source.
    df = (
        df.groupby("h3_id", as_index=False)
        .agg(
            sum_trip=("sum_trip", "sum"),
            trip_class=("trip_class", "mean"),
        )
    )
    return df


def _percent_rank(s):
    n = len(s)
    if n <= 1:
        return pd.Series(np.ones(n), index=s.index)
    return (s.rank(method="min") - 1) / (n - 1)


def _score_period(intersections, h3_data, period):
    x = intersections.merge(h3_data, on="h3_id", how="inner")
    if x.empty:
        return pd.DataFrame()

    g = (
        x.groupby("velo_id", as_index=False)
        .agg(
            h3_count=("h3_id", "nunique"),
            total_trips_reference=("sum_trip", "sum"),
            avg_trips=("sum_trip", "mean"),
            median_trips=("sum_trip", "median"),
            max_trips=("sum_trip", "max"),
            avg_class=("trip_class", "mean"),
            std_trips=("sum_trip", "std"),
        )
    )

    g["std_trips"] = g["std_trips"].fillna(0)
    g["cv"] = np.where(
        g["avg_trips"] > 0,
        g["std_trips"] / g["avg_trips"],
        0,
    )
    g["homogeneity"] = 1 - np.minimum(g["cv"], 1)

    g["rank_avg"] = _percent_rank(g["avg_trips"])
    g["rank_median"] = _percent_rank(g["median_trips"])
    g["rank_max"] = _percent_rank(g["max_trips"])
    g["rank_class"] = _percent_rank(g["avg_class"].fillna(0))

    g["demand_score"] = 100 * (
        0.35 * g["rank_avg"]
        + 0.25 * g["rank_median"]
        + 0.15 * g["rank_max"]
        + 0.15 * g["rank_class"]
        + 0.10 * g["homogeneity"]
    )

    g["period"] = period
    return g


def process_job(input_path, job_dir, data_dir, progress=None):
    job_dir = Path(job_dir)
    data_dir = Path(data_dir)
    job_dir.mkdir(parents=True, exist_ok=True)

    print("=== VELO DEMAND: H3 INDEX MODE ===", flush=True)

    _progress(progress, 5, "Читаем GeoJSON")
    print("[1/6] Reading GeoJSON...", flush=True)
    lanes = _prepare_lanes(input_path)
    print(f"[1/6] Lanes: {len(lanes):,}", flush=True)

    _progress(progress, 15, f"Подготовлено велодорожек: {len(lanes):,}")

    _progress(progress, 20, "Получаем H3 ID для велодорожек")
    print("[2/6] Generating H3 IDs directly from geometry...", flush=True)
    candidates = _build_h3_candidates(lanes)
    unique_candidate_count = candidates["h3_id"].nunique() if not candidates.empty else 0
    print(f"[2/6] Unique H3 candidates: {unique_candidate_count:,}", flush=True)
    _progress(progress, 40, f"Получено H3-кандидатов: {unique_candidate_count:,}")

    _progress(progress, 45, "Проверяем точные пересечения")
    print("[3/6] Exact intersection only for H3 candidates...", flush=True)
    intersections = _make_exact_intersections(lanes, candidates)
    print(f"[3/6] Exact intersections: {len(intersections):,}", flush=True)
    _progress(progress, 50, f"Точных пересечений: {len(intersections):,}")

    del candidates
    gc.collect()

    if intersections.empty:
        raise ValueError(
            "Не найдено ни одного пересечения велодорог с H3. "
            "Проверьте CRS и геометрию GeoJSON."
        )

    needed_h3 = set(intersections["h3_id"].astype(str))
    period_results = []

    for i, (period, filename) in enumerate(PERIODS.items()):
        base = 52 + i * 14
        _progress(progress, base, f"Считаем {period}")
        path = data_dir / filename
        if not path.exists():
            raise FileNotFoundError(f"Не найден файл H3: {path}")

        print(f"[4-6/6] Reading {period}...", flush=True)
        h3_data = _read_h3_period(path, needed_h3=needed_h3)
        print(f"[{period}] Relevant H3 rows: {len(h3_data):,}", flush=True)

        r = _score_period(intersections, h3_data, period)
        if not r.empty:
            period_results.append(r)

        del h3_data, r
        gc.collect()

    if not period_results:
        raise ValueError("Не найдено данных H3 для пересечений.")

    all_periods = pd.concat(period_results, ignore_index=True)

    _progress(progress, 95, "Формируем CSV и GeoJSON")
    print("[6/6] Writing results...", flush=True)

    meta = lanes[["velo_id", "name", "type", "status", "zone"]]
    summary = meta.merge(all_periods, on="velo_id", how="left")

    for period in PERIODS:
        p = summary[summary["period"] == period].copy()
        p.to_csv(
            job_dir / f"velo_demand_{period}.csv",
            index=False,
            encoding="utf-8-sig",
        )

    all_periods.to_csv(
        job_dir / "velo_demand_all_periods.csv",
        index=False,
        encoding="utf-8-sig",
    )

    pivot = all_periods.pivot_table(
        index="velo_id",
        columns="period",
        values="demand_score",
        aggfunc="first",
    ).reset_index()

    for period in PERIODS:
        if period not in pivot.columns:
            pivot[period] = np.nan

    pivot["score_3_periods"] = pivot[list(PERIODS)].mean(axis=1)
    summary_csv = meta.merge(pivot, on="velo_id", how="left")
    summary_csv.to_csv(
        job_dir / "velo_demand_summary_3_periods.csv",
        index=False,
        encoding="utf-8-sig",
    )

    geo = lanes.merge(
        summary_csv,
        on=["velo_id", "name", "type", "status", "zone"],
        how="left",
    )
    geo = geo.replace([np.inf, -np.inf], np.nan)
    geo.to_file(job_dir / "result.geojson", driver="GeoJSON")

    _progress(progress, 100, "Результат готов")
    print("=== DONE ===", flush=True)

    return {
        "lanes": int(len(lanes)),
        "h3_cells": int(unique_candidate_count),
        "h3_candidates": int(unique_candidate_count),
        "intersections": int(len(intersections)),
        "periods": list(PERIODS.keys()),
        "downloads": {
            "geojson": f"/api/download/{job_dir.name}/geojson",
            "summary": f"/api/download/{job_dir.name}/summary",
            "all": f"/api/download/{job_dir.name}/all",
            "24_07": f"/api/download/{job_dir.name}/24_07",
            "25_07": f"/api/download/{job_dir.name}/25_07",
            "26_07": f"/api/download/{job_dir.name}/26_07",
        },
    }
